server:
  port:
    9090



## default connection pool
spring:
  jpa:
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.PostgreSQLDialect"
        jpa:
          hibernate.ddl-auto : none
          show-sql: true
  datasource:
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5

    ## PostgreSQL
    url: jdbc:postgresql://localhost:5440/postgres
    username: "postgres"
    password: "password"
  flyway:
    enabled: true
    locations: classpath:db/migration/postgresql
    schemas: public
    baseline-on-migrate: true

#logging:
#  level:
#    org:
#      hibernate:
#        SQL: DEBUG
#        type:
#          descriptor:
#            sql:
#              BasicBinder: Trace
#
#      springframework:
#        security: DEBUG