version: '3'

services:

  postgresql:
    image: postgres:9.6
    container_name: poll_psql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - 5440:5432
    restart: "no"